### ISSUE TITLE
Save prepare section language in UserDefaults

### ISSUE THREAD

**Issue by jayahariv** [KeralaRescue/KeralaRescueiOS#5]
Currently, it will show English whenever we restart the app. We should save the language preference in UserDefaults. By default the first time it should be English. 

Acceptance
- save the user selected language preference in UserDefaults
- The key should be saved inside the Utility->Constants->UserDefaultsKeys

**Comment by younke** [comment]
I'll take it

**Comment by MaisaMilena** [comment]
Ohhh I've done the issue but I forgot to write here that I was doing D: 
But the is one problem to fix associated with the change of the language

**Comment by jayahariv** [comment]
@younke, if you haven't started this issue, its already fixed by @MaisaMilena.

**Comment by MaisaMilena** [comment]
@younke I agree with you
