### ISSUE TITLE
Localize Home Screen button labels

### ISSUE THREAD

**Issue by jayahariv** [KeralaRescue/KeralaRescueiOS#6]
Localize the home screen button labels

Acceptance
- Use the localization file and create labels for each button titles. 
- Button titles should be programmatically configured & LocalisedString should be taken. 
- Ignore the Malayalam replacement words, I will change that later

**Comment by deepanjali19** [comment]
Hey @jayahariv I am interested to work on this issue. I want to know where is the localization file located.

**Comment by kdaker** [comment]
Added in #10
