### ISSUE TITLE
Localize the Emergency/SOS screen

### ISSUE THREAD

**Issue by jayahariv** [KeralaRescue/KeralaRescueiOS#8]
Emergency/SOS section titles localized

Acceptance
- All strings should programmatically take it from localization file.
- Ignore the Malayalam replacement words, for now, keep it in English but should be easily modifiable to change in the single file.

Below labels
- ViewController title
- Flashlight label
- Strobe light label
- Alarm
- System volume
- Safety Actions
- Safety Actions(Inactive state)
- Mark as Safe 
- Need Help

**Comment by younke** [comment]
I think you should use [Swiftgen](https://github.com/SwiftGen/SwiftGen#) for localizible strings

**Comment by jayahariv** [comment]
@younke thanks for the pointer, I will check that.
